name: CI
on: [push, pull_request]
env:
  MAKEFLAGS: -j3
  BUILD_NUMBER: ${{ github.run_number }}
  MACOSX_DEPLOYMENT_TARGET: '10.13'
jobs:
  macos:
    name: Build on macOS
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --target pkgbuild
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: pkg
        path: build/*.pkg
  windows:
    name: Build on Windows
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Prepare vcpkg
      uses: lukka/run-vcpkg@v6
      id: runvcpkg
      with:
        vcpkgArguments: openssl:x64-windows
        vcpkgDirectory: ${{ runner.workspace }}/vcpkg/
        vcpkgGitCommitId: 8e76503a769e153dad8f4e7b2c95a152bb35edaa
        vcpkgTriplet: x64-windows
    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '5.12.10'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2017_64'
        dir: '${{ github.workspace }}/'
    - name: Build
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=${{ runner.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake -DQt5_DIR=${{ github.workspace }}/Qt/5.15.2/msvc2017_64/lib/cmake/Qt5 ..
        cmake --build . --target installer
    - name: Archive artifacts
      uses: actions/upload-artifact@v2
      with:
        name: msi
        path: build/*.msi