name: CI
on: [push, pull_request]
env:
  BUILD_NUMBER: ${{ github.run_number }}
jobs:
  macos:
    name: Build on macOS
    runs-on: macos-latest
    env:
      MAKEFLAGS: -j3
      MACOSX_DEPLOYMENT_TARGET: 10.15
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Build
      run: |
        cmake -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -S . -B build
        cmake --build build --target pkgbuild
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: pkg
        path: build/*.pkg
  windows:
    name: Build on Windows
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        vcver: [142, 143]
        include:
        - vcver: 142
          image: windows-2019
        - vcver: 143
          image: windows-2022
    env:
      VER_SUFFIX: .VS${{ matrix.vcver }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Prepare vcpkg
      uses: lukka/run-vcpkg@v7
      id: runvcpkg
      with:
        vcpkgArguments: openssl
        vcpkgGitCommitId: 9b9c2758ece1d8ac0de90589730bb5ccf45c0874
        vcpkgTriplet: x64-windows
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.5.1
        arch: win64_msvc2019_64
        modules: qt5compat
    - name: Setup dev env
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Build
      run: |
        cmake -S . -B build `
          -DCMAKE_TOOLCHAIN_FILE=${{ env.RUNVCPKG_VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
        cmake --build build --target installer
    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: msi
        path: build/*.msi
