name: CI
on: [push, pull_request]
env:
  BUILD_NUMBER: ${{ github.run_number }}
  CMAKE_BUILD_PARALLEL_LEVEL: 4
jobs:
  macos:
    name: Build on macOS
    runs-on: macos-latest
    env:
      MACOSX_DEPLOYMENT_TARGET: 12.0
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Build
      run: |
        cmake -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" -S . -B build
        cmake --build build --target pkgbuild
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macOS
        path: build/*.pkg
  windows:
    name: Build on Windows
    runs-on: ${{ matrix.image }}
    strategy:
      matrix:
        vcver: [142, 143]
        include:
        - vcver: 142
          image: windows-2019
        - vcver: 143
          image: windows-2022
    env:
      VER_SUFFIX: .VS${{ matrix.vcver }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Prepare vcpkg
      uses: lukka/run-vcpkg@v7
      id: runvcpkg
      with:
        vcpkgArguments: openssl
        vcpkgGitCommitId: 8161f655436492669adc8eb6f269dc41392ffa70
        vcpkgTriplet: x64-windows
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: 6.7.1
        arch: win64_msvc2019_64
    - name: Setup dev env
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
    - name: Install WiX
      run: |
        dotnet tool install -g wix --version 5.0.0
        wix extension -g add WixToolset.UI.wixext/5.0.0
    - name: Build
      run: |
        cmake -S . -B build `
          -DCMAKE_TOOLCHAIN_FILE=${{ env.RUNVCPKG_VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake
        cmake --build build --target installer
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: msi_${{ matrix.vcver }}_x64
        path: build/*.msi
